name: 自動ポスト生成＆WordPress公開

on:
  workflow_dispatch:

jobs:
  generate_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    # ここで secrets を環境変数として渡す
    env:
      OPENAI_API_KEY:  ${{ secrets.OPENAI_API_KEY }}
      WP_URL:          ${{ secrets.WP_URL }}
      WP_USERNAME:     ${{ secrets.WP_USERNAME }}
      WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}

    steps:
      - name: コードをチェックアウト
        uses: actions/checkout@v4

      - name: Python セットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 依存ライブラリをインストール
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install markdown requests

      - name: 記事を生成
        run: python post.py

      - name: WordPress 投稿をデバッグ
        run: |
          echo "WP_URL=$WP_URL"
          echo "WP_USERNAME=$WP_USERNAME"
          echo "WP_APP_PASSWORD=${WP_APP_PASSWORD:0:4}****"

      - name: WordPress に投稿（タグなし）
        run: python scripts/wp_post.py

      - name: 生成記事をコミット＆プッシュ
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add posts/
          git diff --quiet || git commit -m "chore: 自動生成記事を追加"
          git push

