name: 自動ポスト生成＆WordPress公開

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # 毎日 09:00 JST に実行

jobs:
  generate_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      OPENAI_API_KEY:  ${{ secrets.OPENAI_API_KEY }}
      WP_URL:          ${{ secrets.WP_URL }}
      WP_USERNAME:     ${{ secrets.WP_USERNAME }}
      WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}

    steps:
      - name: コードをチェックアウト
        uses: actions/checkout@v4

      - name: Python セットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 依存ライブラリをインストール
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install markdown requests

      - name: 記事を生成（ChatGPTで）
        run: python post.py

      - name: payload.json を生成（投稿データ＋SEOメタ）
        run: python scripts/wp_post.py

      - name: WordPress に投稿（AIOSEO対応）
        run: |
          echo "== CURLで投稿 =="
          curl -i -X POST \
            -u "${WP_USERNAME}:${WP_APP_PASSWORD}" \
            -H "Content-Type: application/json; charset=UTF-8" \
            --data-binary @payload.json \
            "${WP_URL}/wp-json/wp/v2/posts"

      - name: 生成記事をコミット＆プッシュ
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add posts/ payload.json
          git diff --quiet || git commit -m "chore: 自動生成記事を追加"
          git push
